version: "3"

services:
  grafana.loki:
    image: grafana/loki:latest
    container_name: "grafana.loki"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
#    volumes:
#          - loki_data_container:/loki # save to volume

  grafana.alloy:
    image: grafana/alloy:latest
    container_name: "grafana.alloy"
    ports:
      - "12345:12345"
    volumes:
      - ./devops/grafana/config.alloy:/etc/alloy/config.alloy
    entrypoint: ["alloy", "run", "/etc/alloy/config.alloy"]
    command:
      - --server.http.listen-addr=0.0.0.0:12345
  
  grafana.tempo:
    image: grafana/tempo:latest
    container_name: "grafana.tempo"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./devops/grafana/tempo.yaml:/etc/tempo.yaml
#      - tempo_data_container:/var/tempo # save to volume
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./devops/grafana/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
    volumes:
      - ./devops/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        
#volumes:
#  loki_data_container:
#  tempo_data_container:
