services:
  roa.db:
    container_name: "roa.db"
    image: mongo:latest
    labels:
      - "app.roa"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  roa.rest.api:
    image: roa.rest.api
    container_name: "roa.rest.api"
    labels:
      - "app.roa"
      - "app.roa.api"
    depends_on:
      - "roa.db"
    build:
      context: .
      dockerfile: ROA.Rest.API/Dockerfile
    ports:
      - "5200:8080"
    volumes:
      - api_data_protection_container:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  roa.db.migrations:
    image: roa-db-migrations
    container_name: "roa.db.migrations"
    labels:
      - "app.roa"
    depends_on:
      - "roa.db"
    build:
      context: .
      dockerfile: Roa.Data.Migrations/Dockerfile

volumes:
  mongodb_data_container:
  api_data_protection_container:
    